In [1]:
from sklearn.decomposition import PCA
import numpy as np
from pandas import DataFrame 
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
from sklearn.decomposition import FastICA
from sklearn.manifold import TSNE 
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.manifold import LocallyLinearEmbedding
from sklearn import manifold 
from sklearn.decomposition import KernelPCA
from sklearn.model_selection import train_test_split

In [2]:
Y=np.loadtxt('Reflection2_00001.txt').T[0,]
X=pd.read_csv('Coffee.csv')

In [3]:
X.head()

0      1       2        3       4       5       6       7      8  \
0 -16.25 -16.25 -240.85 -1143.43    5.30 -1398.4  -76.50  -50.34 -54.64   
1  91.77  91.77   -1.07  -587.88  260.37  1400.0  145.75  108.58  56.00   
2 -13.58 -13.58  -61.63  1912.12 -272.99 -2794.4  -57.48   -3.32 -11.25   
3  70.66  70.66   70.16   302.02  -32.04  -392.8   69.40   39.39  11.25   
4  -0.50  -0.50 -230.02  -451.52    6.97 -1332.0  -27.87  -13.09  67.55   

        9  ...   2038   2039   2040   2041   2042   2043   2044   2045   2046  \
0  180.18  ...  41.45  43.18  45.36  41.60  44.82  45.09  44.30  37.59  34.43   
1  138.30  ...  40.41  39.10  41.98  44.47  42.77  40.35  35.54  36.05  34.25   
2   18.49  ...  41.36  40.69  39.10  38.15  40.30  38.80  35.84  31.21  30.54   
3  180.90  ...  38.66  40.27  41.95  37.70  37.94  33.92  33.46  30.35  29.20   
4   24.62  ...  40.32  40.45  38.35  36.67  39.95  40.73  41.18  37.72  37.03   

    2047  
0  34.43  
1  34.25  
2  30.54  
3  29.20  
4  37.03  

[5 rows x 2048 columns]

In [4]:
Y[300],Y[1600]

(325.441, 865.397)

In [5]:
x=X.T
X_n=x[300:1600].T
X_n.shape

(890, 1300)

In [6]:
pca=PCA(n_components=11)
X_PCA=pca.fit_transform(X_n)
ICA = FastICA(n_components=11,random_state=400) 
X_ICA=ICA.fit_transform(X_n)

In [7]:
X_tsne = TSNE(n_components=3, n_iter=800).fit_transform(X_n)

In [8]:
lle=LocallyLinearEmbedding(n_components=16,n_neighbors=40)
X_lle=lle.fit_transform(X_n)

In [9]:
from numpy import array

In [10]:
# first use 1,2,3,...to present the different class:
# "0": unlabeled
# "1": health good
# "2": rust
# "3": infected green canopy
# "4": geisha
# "5": geisha cannopy
# "6": yellow
# "7": yellow green
# "8": Young_Rust_Yellow
# "9": Young_Rust_Green_Leaf
target=array(["1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1",
             "1","1","1","1","1","1","1","1","1","1","0","0","0","0","0","0","0","0","0","0","8","8","8","8","8","8","8","8","8","8",
             "8","8","8","8","8","8","8","8","8","8","0","0","0","0","0","0","0","0","0","0","9","9","9","9","9","9","9","9","9","9",
             "0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0",
             "0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0",
             "0","0","0","0","0","0","0","0","0","0","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1",
             "1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1",
             "1","1","1","1","1","1","1","1","1","1","0","0","0","0","0","0","0","0","0","0","1","1","1","1","1","1","1","1","1","1",
             "1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","2","2","2","2","2","2","2","2","2","2",
             "2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2",
             "3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3",
             "2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2",
             "2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2",
             "2","2","2","2","2","2","2","2","2","2","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3",
             "3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","2","2","2","2","2","2","2","2","2","2",
             "2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2",
             "2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2",
             "2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","3","3","3","3","3","3","3","3","3","3",
             "3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","1","1","1","1","1","1","1","1","1","1",
             "1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1",
             "0","0","0","0","0","0","0","0","0","0","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1",
             "1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1",
             "1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","4","4","4","4","4","4","4","4","4","4",
             "4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4",
             "4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4",
             "4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4",
             "4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","0","0","0","0","0","0","0","0","0","0",
             "4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4",
             "5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5",
             "5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5"])

target_labeled=array(["1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1",
             "1","1","1","1","1","1","1","1","1","1",
             "1","1","1","1","1","1","1","1","1","1","8","8","8","8","8","8","8","8","8","8",
             "8","8","8","8","8","8","8","8","8","8","9","9","9","9","9","9","9","9","9","9",
             "1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1",
             "1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1",
             "1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1",
             "1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","2","2","2","2","2","2","2","2","2","2",
             "2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2",
             "3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3",
             "2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2",
             "2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2",
             "2","2","2","2","2","2","2","2","2","2","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3",
             "3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","2","2","2","2","2","2","2","2","2","2",
             "2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2",
             "2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2",
             "2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","3","3","3","3","3","3","3","3","3","3",
             "3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","1","1","1","1","1","1","1","1","1","1",
             "1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1",
             "1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1",
             "1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1",
             "1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","1","4","4","4","4","4","4","4","4","4","4",
             "4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4",
             "4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4",
             "4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4",
             "4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4",
             "4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4","4",
             "5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5",
             "5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5","5"])

target_unlabeled=array(["0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0",
             "0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0",
             "0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0",
             "0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0",
             "0","0","0","0","0","0","0","0","0","0"])


In [11]:
np.savetxt('New_X',X_n)
np.savetxt("PCA",X_PCA)
np.savetxt("ICA",X_ICA)
np.savetxt("LLE",X_lle)
np.savetxt('TSNE',X_tsne)

In [12]:
X_new=np.loadtxt('New_X')
X_Pca=np.loadtxt("PCA")
X_ICA=np.loadtxt("ICA")
X_lle=np.loadtxt("LLE")
X_tsne=np.loadtxt("TSNE")

In [13]:
X.shape

(890, 2048)

In [14]:
X_tsne_labeled=np.vstack((X_tsne[0:40],X_tsne[50:70],X_tsne[80:90],X_tsne[160:220],X_tsne[230:600],X_tsne[610:800],X_tsne[810:890]))
X_tsne_unlabeled=np.vstack((X_tsne[40:50],X_tsne[70:80],X_tsne[90:160],X_tsne[220:230],X_tsne[600:610],X_tsne[800:810]))
X_Pca_labeled=np.vstack((X_Pca[0:40],X_Pca[50:70],X_Pca[80:90],X_Pca[160:220],X_Pca[230:600],X_Pca[610:800],X_Pca[810:890]))
X_Pca_unlabeled=np.vstack((X_Pca[40:50],X_Pca[70:80],X_Pca[90:160],X_Pca[220:230],X_Pca[600:610],X_Pca[800:810]))
X_ICA_labeled=np.vstack((X_ICA[0:40],X_ICA[50:70],X_ICA[80:90],X_ICA[160:220],X_ICA[230:600],X_ICA[610:800],X_ICA[810:890]))
X_ICA_unlabeled=np.vstack((X_ICA[40:50],X_ICA[70:80],X_ICA[90:160],X_ICA[220:230],X_ICA[600:610],X_ICA[800:810]))
X_lle_labeled=np.vstack((X_lle[0:40],X_lle[50:70],X_lle[80:90],X_lle[160:220],X_lle[230:600],X_lle[610:800],X_lle[810:890]))
X_lle_unlabeled=np.vstack((X_lle[40:50],X_lle[70:80],X_lle[90:160],X_lle[220:230],X_lle[600:610],X_lle[800:810]))
X_labeled=np.vstack((X_new[0:40],X_new[50:70],X_new[80:90],X_new[160:220],X_new[230:600],X_new[610:800],X_new[810:890]))
X_unlabeled=np.vstack((X_new[40:50],X_new[70:80],X_new[90:160],X_new[220:230],X_new[600:610],X_new[800:810]))

In [15]:
x_train, x_test, y_train, y_test = train_test_split(X_labeled,target_labeled, test_size=0.3)
xpca_train, xpca_test, ypca_train, ypca_test = train_test_split(X_Pca_labeled,target_labeled, test_size=0.3)
xIca_train, xIca_test, yIca_train, yIca_test = train_test_split(X_ICA_labeled,target_labeled, test_size=0.3)
xlle_train, xlle_test, ylle_train, ylle_test = train_test_split(X_lle_labeled,target_labeled, test_size=0.3)
xtsne_train, xtsne_test, ytsne_train, ytsne_test = train_test_split(X_tsne_labeled,target_labeled, test_size=0.3)

In [16]:
from sklearn import svm
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import matthews_corrcoef
from sklearn.model_selection import RandomizedSearchCV

In [17]:
SVM= SVC(kernel='rbf')
distributions = dict(C=np.logspace(-3,3,50),gamma=np.logspace(-3,3,50))
clf = RandomizedSearchCV(SVM, distributions, random_state=50)

In [18]:
search1 = clf.fit(x_train, y_train)
search1.best_params_ 

C:\Users\user\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


{'gamma': 0.0030888435964774815, 'C': 4.714866363457395}

In [19]:
SVM= SVC(kernel='rbf')
distributions = dict(C=np.logspace(-3,3,50),gamma=np.logspace(-3,3,50))
clf = RandomizedSearchCV(SVM, distributions, random_state=50)

In [20]:
search2 = clf.fit(xpca_train, ypca_train)
search2.best_params_ 

C:\Users\user\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


{'gamma': 0.0030888435964774815, 'C': 4.714866363457395}

In [21]:
from sklearn.ensemble import BaggingClassifier

In [22]:
clf= SVC(C=4.7,kernel='rbf',gamma=0.003)

In [23]:
bagging = BaggingClassifier(clf,max_samples=0.6, max_features=0.6)

In [24]:
bagging.fit(x_train,y_train)

BaggingClassifier(base_estimator=SVC(C=4.7, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.003, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
         bootstrap=True, bootstrap_features=False, max_features=0.6,
         max_samples=0.6, n_estimators=10, n_jobs=None, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [25]:
print ('accuracy_train：', accuracy_score(y_train, bagging.predict(x_train)))
print ('accuracy_test：', accuracy_score(y_test, bagging.predict(x_test)))
print ('Kappa_train：', cohen_kappa_score(y_train, bagging.predict(x_train)))
print ('Kappa_test：', cohen_kappa_score(y_test, bagging.predict(x_test)))

print ('confusion_matrix_train：')
print ( confusion_matrix(y_train, bagging.predict(x_train)))
print ('confusion_matrix_test：')
print ( confusion_matrix(y_test, bagging.predict(x_test)))

accuracy_train： 0.9313543599257885
accuracy_test： 0.8095238095238095
Kappa_train： 0.909601062503683
Kappa_test： 0.7484096140993589
confusion_matrix_train：
[[173   0   1   1   0   0   0]
 [  4 132   0   0   0   0   0]
 [  6   0  61   0   0   0   0]
 [  6   0   0  99   0   0   0]
 [ 11   0   0   0  21   0   0]
 [  3   0   0   0   0  13   0]
 [  5   0   0   0   0   0   3]]
confusion_matrix_test：
[[64  0  1  0  0  0  0]
 [12 52  0  0  0  0  0]
 [11  0 22  0  0  0  0]
 [ 5  0  0 40  0  0  0]
 [12  0  0  0  6  0  0]
 [ 1  0  0  0  0  3  0]
 [ 2  0  0  0  0  0  0]]


In [26]:
clf.fit(x_train, y_train)
print ('accuracy_train：', accuracy_score(y_train, clf.predict(x_train)))
print ('accuracy_test：', accuracy_score(y_test, clf.predict(x_test)))

print ('Kappa_train：', cohen_kappa_score(y_train, clf.predict(x_train)))
print ('Kappa_test：', cohen_kappa_score(y_test, clf.predict(x_test)))

print ('confusion_matrix_train：')
print ( confusion_matrix(y_train, clf.predict(x_train)))
print ('confusion_matrix_test：')
print ( confusion_matrix(y_test, clf.predict(x_test)))

accuracy_train： 1.0
accuracy_test： 0.8441558441558441
Kappa_train： 1.0
Kappa_test： 0.7948034643570953
confusion_matrix_train：
[[175   0   0   0   0   0   0]
 [  0 136   0   0   0   0   0]
 [  0   0  67   0   0   0   0]
 [  0   0   0 105   0   0   0]
 [  0   0   0   0  32   0   0]
 [  0   0   0   0   0  16   0]
 [  0   0   0   0   0   0   8]]
confusion_matrix_test：
[[65  0  0  0  0  0  0]
 [ 9 55  0  0  0  0  0]
 [ 8  0 25  0  0  0  0]
 [ 5  0  0 40  0  0  0]
 [12  0  0  0  6  0  0]
 [ 0  0  0  0  0  4  0]
 [ 2  0  0  0  0  0  0]]


In [77]:
clf1= SVC(C=2,kernel='rbf',gamma=0.003)

In [78]:
bagging1 = BaggingClassifier(clf1,max_samples=0.6, max_features=0.6)
bagging1.fit(xpca_train,ypca_train)

BaggingClassifier(base_estimator=SVC(C=2, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.003, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
         bootstrap=True, bootstrap_features=False, max_features=0.6,
         max_samples=0.6, n_estimators=10, n_jobs=None, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [79]:
bagging1.fit(xpca_train, ypca_train)
print ('accuracy_train：', accuracy_score(ypca_train, bagging1.predict(xpca_train)))
print ('accuracy_test：', accuracy_score(ypca_test, bagging1.predict(xpca_test)))

print ('Kappa_train：', cohen_kappa_score(ypca_train, bagging1.predict(xpca_train)))
print ('Kappa_test：', cohen_kappa_score(ypca_test, bagging1.predict(xpca_test)))

print ('confusion_matrix_train：')
print ( confusion_matrix(ypca_train, bagging1.predict(xpca_train)))
print ('confusion_matrix_test：')
print ( confusion_matrix(ypca_test, bagging1.predict(xpca_test)))

accuracy_train： 0.948051948051948
accuracy_test： 0.8658008658008658
Kappa_train： 0.9328067816532061
Kappa_test： 0.8212788259958071
confusion_matrix_train：
[[158   1   1   2   0   0   0]
 [  0 141   0   0   0   0   0]
 [  3   2  69   0   0   0   0]
 [  3   0   0  99   0   0   0]
 [  0  12   0   0  27   0   0]
 [  0   1   0   0   0  13   0]
 [  2   1   0   0   0   0   4]]
confusion_matrix_test：
[[68  3  5  2  0  0  0]
 [ 0 59  0  0  0  0  0]
 [ 2  1 23  0  0  0  0]
 [ 5  0  0 43  0  0  0]
 [ 0  9  0  0  2  0  0]
 [ 0  1  0  0  0  5  0]
 [ 1  2  0  0  0  0  0]]


In [80]:
clf1.fit(xpca_train, ypca_train)
print ('accuracy_train：', accuracy_score(ypca_train, clf1.predict(xpca_train)))
print ('accuracy_test：', accuracy_score(ypca_test, clf1.predict(xpca_test)))

print ('Kappa_train：', cohen_kappa_score(ypca_train, clf1.predict(xpca_train)))
print ('Kappa_test：', cohen_kappa_score(ypca_test, clf1.predict(xpca_test)))

print ('confusion_matrix_train：')
print ( confusion_matrix(ypca_train, clf1.predict(xpca_train)))
print ('confusion_matrix_test：')
print ( confusion_matrix(ypca_test, clf1.predict(xpca_test)))

accuracy_train： 1.0
accuracy_test： 0.8658008658008658
Kappa_train： 1.0
Kappa_test： 0.8207957957957959
confusion_matrix_train：
[[162   0   0   0   0   0   0]
 [  0 141   0   0   0   0   0]
 [  0   0  74   0   0   0   0]
 [  0   0   0 102   0   0   0]
 [  0   0   0   0  39   0   0]
 [  0   0   0   0   0  14   0]
 [  0   0   0   0   0   0   7]]
confusion_matrix_test：
[[69  6  1  2  0  0  0]
 [ 0 59  0  0  0  0  0]
 [ 2  2 22  0  0  0  0]
 [ 2  3  0 43  0  0  0]
 [ 0  9  0  0  2  0  0]
 [ 0  1  0  0  0  5  0]
 [ 0  3  0  0  0  0  0]]


In [31]:
SVM= SVC(kernel='rbf')
distributions = dict(C=np.logspace(-3,1,50),gamma=np.logspace(-3,2,50))
clf = RandomizedSearchCV(SVM, distributions, random_state=50)

In [32]:
search4 = clf.fit(xtsne_train, ytsne_train)
search4.best_params_ 

C:\Users\user\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


{'gamma': 0.5689866029018299, 'C': 4.714866363457389}

In [33]:
clf2= SVC(C=4.7,kernel='rbf',gamma=0.57)

In [34]:
clf2.fit(xtsne_train, ytsne_train)
print ('accuracy_train：', accuracy_score(ytsne_train, clf2.predict(xtsne_train)))
print ('accuracy_test：', accuracy_score(ytsne_test, clf2.predict(xtsne_test)))

print ('Kappa_train：', cohen_kappa_score(ytsne_train, clf2.predict(xtsne_train)))
print ('Kappa_test：', cohen_kappa_score(ytsne_test, clf2.predict(xtsne_test)))

print ('confusion_matrix_train：')
print ( confusion_matrix(ytsne_train, clf2.predict(xtsne_train)))
print ('confusion_matrix_test：')
print ( confusion_matrix(ytsne_test, clf2.predict(xtsne_test)))

accuracy_train： 0.9758812615955473
accuracy_test： 0.948051948051948
Kappa_train： 0.968759752824418
Kappa_test： 0.9330208282994249
confusion_matrix_train：
[[161   0   2   1   0   0   0]
 [  0 146   0   0   0   0   0]
 [  4   0  64   1   0   0   0]
 [  5   0   0 102   0   0   0]
 [  0   0   0   0  34   0   0]
 [  0   0   0   0   0  12   0]
 [  0   0   0   0   0   0   7]]
confusion_matrix_test：
[[72  0  1  2  0  0  1]
 [ 0 54  0  0  0  0  0]
 [ 2  0 29  0  0  0  0]
 [ 5  0  0 38  0  0  0]
 [ 0  0  0  0 16  0  0]
 [ 0  0  0  0  0  8  0]
 [ 1  0  0  0  0  0  2]]


In [35]:
SVM= SVC(kernel='rbf')
distributions = dict(C=np.logspace(-3,2,50),gamma=np.logspace(-3,2,50))
clf = RandomizedSearchCV(SVM, distributions, random_state=50)

In [36]:
search3 = clf.fit(xIca_train, yIca_train)
search3.best_params_ 

C:\Users\user\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


{'gamma': 24.420530945486497, 'C': 19.306977288832496}

In [67]:
clf3= SVC(C=40,kernel='rbf',gamma=24)

In [68]:
clf3.fit(xIca_train, yIca_train)
print ('accuracy_train：', accuracy_score(yIca_train, clf3.predict(xIca_train)))
print ('accuracy_test：', accuracy_score(yIca_test, clf3.predict(xIca_test)))

print ('Kappa_train：', cohen_kappa_score(yIca_train, clf3.predict(xIca_train)))
print ('Kappa_test：', cohen_kappa_score(yIca_test, clf3.predict(xIca_test)))

print ('confusion_matrix_train：')
print ( confusion_matrix(yIca_train, clf3.predict(xIca_train)))
print ('confusion_matrix_test：')
print ( confusion_matrix(yIca_test, clf3.predict(xIca_test)))

accuracy_train： 0.9332096474953617
accuracy_test： 0.9264069264069265
Kappa_train： 0.9137423651057549
Kappa_test： 0.9048876186785506
confusion_matrix_train：
[[164   0   5   6   0   0   0]
 [  0 135   0   0   0   0   0]
 [ 10   0  57   7   0   0   0]
 [  0   0   8  91   0   0   0]
 [  0   0   0   0  34   0   0]
 [  0   0   0   0   0  14   0]
 [  0   0   0   0   0   0   8]]
confusion_matrix_test：
[[60  0  1  4  0  0  0]
 [ 0 65  0  0  0  0  0]
 [ 4  0 19  3  0  0  0]
 [ 1  0  4 46  0  0  0]
 [ 0  0  0  0 16  0  0]
 [ 0  0  0  0  0  6  0]
 [ 0  0  0  0  0  0  2]]


In [39]:
SVM= SVC(kernel='rbf')
distributions = dict(C=np.logspace(-3,2,50),gamma=np.logspace(-3,2,50))
clf = RandomizedSearchCV(SVM, distributions, random_state=50)

In [40]:
search5 = clf.fit(xlle_train, ylle_train)
search5.best_params_ 

C:\Users\user\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


{'gamma': 24.420530945486497, 'C': 19.306977288832496}

In [41]:
clf4= SVC(C=20,kernel='rbf',gamma=24)

In [42]:
clf4.fit(xlle_train, ylle_train)
print ('accuracy_train：', accuracy_score(ylle_train, clf4.predict(xlle_train)))
print ('accuracy_test：', accuracy_score(ylle_test, clf4.predict(xlle_test)))

print ('Kappa_train：', cohen_kappa_score(ylle_train, clf4.predict(xlle_train)))
print ('Kappa_test：', cohen_kappa_score(ylle_test, clf4.predict(xlle_test)))

print ('confusion_matrix_train：')
print ( confusion_matrix(ylle_train, clf4.predict(xlle_train)))
print ('confusion_matrix_test：')
print ( confusion_matrix(ylle_test, clf4.predict(xlle_test)))

accuracy_train： 0.922077922077922
accuracy_test： 0.8744588744588745
Kappa_train： 0.8994353846358875
Kappa_test： 0.8358289425315525
confusion_matrix_train：
[[149   0  14   0   0   0   0]
 [  0 144   0   0   0   0   0]
 [ 17   0  50   0   0   0   0]
 [  5   0   6  97   0   0   0]
 [  0   0   0   0  38   0   0]
 [  0   0   0   0   0  12   0]
 [  0   0   0   0   0   0   7]]
confusion_matrix_test：
[[69  0  7  1  0  0  0]
 [ 0 56  0  0  0  0  0]
 [13  0 20  0  0  0  0]
 [ 6  0  2 34  0  0  0]
 [ 0  0  0  0 12  0  0]
 [ 0  0  0  0  0  8  0]
 [ 0  0  0  0  0  0  3]]


In [43]:
from sklearn import tree
clf_tree = tree.DecisionTreeClassifier(max_depth=9)

In [44]:
clf_tree.fit(x_train, y_train)
print ('accuracy_train：', accuracy_score(y_train, clf_tree.predict(x_train)))
print ('accuracy_test：', accuracy_score(y_test, clf_tree.predict(x_test)))

print ('Kappa_train：', cohen_kappa_score(y_train, clf_tree.predict(x_train)))
print ('Kappa_test：', cohen_kappa_score(y_test, clf_tree.predict(x_test)))

print ('confusion_matrix_train：')
print ( confusion_matrix(y_train, clf_tree.predict(x_train)))
print ('confusion_matrix_test：')
print ( confusion_matrix(y_test, clf_tree.predict(x_test)))

accuracy_train： 0.9461966604823747
accuracy_test： 0.8917748917748918
Kappa_train： 0.9297325241627332
Kappa_test： 0.8608668417375382
confusion_matrix_train：
[[174   0   1   0   0   0   0]
 [  0 136   0   0   0   0   0]
 [ 12   0  55   0   0   0   0]
 [ 14   0   2  89   0   0   0]
 [  0   0   0   0  32   0   0]
 [  0   0   0   0   0  16   0]
 [  0   0   0   0   0   0   8]]
confusion_matrix_test：
[[60  0  1  4  0  0  0]
 [ 0 60  0  0  4  0  0]
 [ 6  0 27  0  0  0  0]
 [ 7  0  2 36  0  0  0]
 [ 0  0  0  0 18  0  0]
 [ 0  0  0  0  0  4  0]
 [ 1  0  0  0  0  0  1]]


In [45]:
clf_tree.fit(xpca_train, ypca_train)
print ('accuracy_train：', accuracy_score(ypca_train, clf_tree.predict(xpca_train)))
print ('accuracy_test：', accuracy_score(ypca_test, clf_tree.predict(xpca_test)))

print ('Kappa_train：', cohen_kappa_score(ypca_train, clf_tree.predict(xpca_train)))
print ('Kappa_test：', cohen_kappa_score(ypca_test, clf_tree.predict(xpca_test)))

print ('confusion_matrix_train：')
print ( confusion_matrix(ypca_train, clf_tree.predict(xpca_train)))
print ('confusion_matrix_test：')
print ( confusion_matrix(ypca_test, clf_tree.predict(xpca_test)))

accuracy_train： 0.9795918367346939
accuracy_test： 0.9047619047619048
Kappa_train： 0.9738960066922027
Kappa_test： 0.8762238784158994
confusion_matrix_train：
[[155   0   7   0   0   0   0]
 [  0 141   0   0   0   0   0]
 [  3   0  71   0   0   0   0]
 [  0   0   1 101   0   0   0]
 [  0   0   0   0  39   0   0]
 [  0   0   0   0   0  14   0]
 [  0   0   0   0   0   0   7]]
confusion_matrix_test：
[[64  0  9  5  0  0  0]
 [ 0 59  0  0  0  0  0]
 [ 2  0 22  2  0  0  0]
 [ 1  0  0 47  0  0  0]
 [ 0  0  0  1  9  0  1]
 [ 0  0  0  0  0  6  0]
 [ 0  0  0  0  0  1  2]]


In [46]:
clf_tree.fit(xIca_train, yIca_train)
print ('accuracy_train：', accuracy_score(yIca_train, clf_tree.predict(xIca_train)))
print ('accuracy_test：', accuracy_score(yIca_test, clf_tree.predict(xIca_test)))

print ('Kappa_train：', cohen_kappa_score(yIca_train, clf_tree.predict(xIca_train)))
print ('Kappa_test：', cohen_kappa_score(yIca_test, clf_tree.predict(xIca_test)))

print ('confusion_matrix_train：')
print ( confusion_matrix(yIca_train, clf_tree.predict(xIca_train)))
print ('confusion_matrix_test：')
print ( confusion_matrix(yIca_test, clf_tree.predict(xIca_test)))

accuracy_train： 0.9777365491651205
accuracy_test： 0.9177489177489178
Kappa_train： 0.9713096938458672
Kappa_test： 0.8935741998060136
confusion_matrix_train：
[[168   0   7   0   0   0   0]
 [  0 134   1   0   0   0   0]
 [  0   0  74   0   0   0   0]
 [  4   0   0  95   0   0   0]
 [  0   0   0   0  34   0   0]
 [  0   0   0   0   0  14   0]
 [  0   0   0   0   0   0   8]]
confusion_matrix_test：
[[60  2  1  1  0  1  0]
 [ 0 64  0  0  0  0  1]
 [ 2  0 24  0  0  0  0]
 [ 8  0  1 42  0  0  0]
 [ 0  1  0  0 15  0  0]
 [ 0  1  0  0  0  5  0]
 [ 0  0  0  0  0  0  2]]


In [47]:
clf_tree.fit(xlle_train, ylle_train)
print ('accuracy_train：', accuracy_score(ylle_train, clf_tree.predict(xlle_train)))
print ('accuracy_test：', accuracy_score(ylle_test, clf_tree.predict(xlle_test)))

print ('Kappa_train：', cohen_kappa_score(ylle_train, clf_tree.predict(xlle_train)))
print ('Kappa_test：', cohen_kappa_score(ylle_test, clf_tree.predict(xlle_test)))

print ('confusion_matrix_train：')
print ( confusion_matrix(ylle_train, clf_tree.predict(xlle_train)))
print ('confusion_matrix_test：')
print ( confusion_matrix(ylle_test, clf_tree.predict(xlle_test)))

accuracy_train： 0.9888682745825603
accuracy_test： 0.9047619047619048
Kappa_train： 0.9856538287508984
Kappa_test： 0.877187046882552
confusion_matrix_train：
[[160   0   3   0   0   0   0]
 [  0 144   0   0   0   0   0]
 [  3   0  64   0   0   0   0]
 [  0   0   0 108   0   0   0]
 [  0   0   0   0  38   0   0]
 [  0   0   0   0   0  12   0]
 [  0   0   0   0   0   0   7]]
confusion_matrix_test：
[[64  0  8  4  1  0  0]
 [ 0 56  0  0  0  0  0]
 [ 5  0 27  1  0  0  0]
 [ 1  0  0 41  0  0  0]
 [ 1  0  0  0 11  0  0]
 [ 0  0  0  0  0  8  0]
 [ 1  0  0  0  0  0  2]]


In [48]:
clf_tree.fit(xtsne_train, ytsne_train)
print ('accuracy_train：', accuracy_score(ytsne_train, clf_tree.predict(xtsne_train)))
print ('accuracy_test：', accuracy_score(ytsne_test, clf_tree.predict(xtsne_test)))

print ('Kappa_train：', cohen_kappa_score(ytsne_train, clf_tree.predict(xtsne_train)))
print ('Kappa_test：', cohen_kappa_score(ytsne_test, clf_tree.predict(xtsne_test)))

print ('confusion_matrix_train：')
print ( confusion_matrix(ytsne_train, clf_tree.predict(xtsne_train)))
print ('confusion_matrix_test：')
print ( confusion_matrix(ytsne_test, clf_tree.predict(xtsne_test)))

accuracy_train： 0.9406307977736549
accuracy_test： 0.8571428571428571
Kappa_train： 0.9225379944669996
Kappa_test： 0.8127487103905674
confusion_matrix_train：
[[162   0   0   2   0   0   0]
 [  1 145   0   0   0   0   0]
 [ 12   0  57   0   0   0   0]
 [ 16   0   0  91   0   0   0]
 [  1   0   0   0  33   0   0]
 [  0   0   0   0   0  12   0]
 [  0   0   0   0   0   0   7]]
confusion_matrix_test：
[[71  0  2  3  0  0  0]
 [ 0 54  0  0  0  0  0]
 [11  0 20  0  0  0  0]
 [12  0  0 30  0  1  0]
 [ 0  0  0  1 15  0  0]
 [ 0  0  0  0  0  8  0]
 [ 1  0  0  1  1  0  0]]


In [49]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

In [50]:
randomforest = RandomForestClassifier(max_depth=8)

In [51]:
randomforest.fit(x_train, y_train)
print ('accuracy_train：', accuracy_score(y_train, randomforest.predict(x_train)))
print ('accuracy_test：', accuracy_score(y_test, randomforest.predict(x_test)))

print ('Kappa_train：', cohen_kappa_score(y_train, randomforest.predict(x_train)))
print ('Kappa_test：', cohen_kappa_score(y_test, randomforest.predict(x_test)))

print ('confusion_matrix_train：')
print ( confusion_matrix(y_train, randomforest.predict(x_train)))
print ('confusion_matrix_test：')
print ( confusion_matrix(y_test, randomforest.predict(x_test)))

accuracy_train： 0.9758812615955473
accuracy_test： 0.9307359307359307
Kappa_train： 0.9688594386077187
Kappa_test： 0.9108000482683721
confusion_matrix_train：
[[168   0   6   1   0   0   0]
 [  0 136   0   0   0   0   0]
 [  2   0  64   1   0   0   0]
 [  1   0   2 102   0   0   0]
 [  0   0   0   0  32   0   0]
 [  0   0   0   0   0  16   0]
 [  0   0   0   0   0   0   8]]
confusion_matrix_test：
[[62  0  2  1  0  0  0]
 [ 0 64  0  0  0  0  0]
 [ 2  0 27  4  0  0  0]
 [ 4  0  2 39  0  0  0]
 [ 0  0  0  0 18  0  0]
 [ 0  0  0  0  0  4  0]
 [ 1  0  0  0  0  0  1]]


C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [52]:
randomforest.fit(xpca_train, ypca_train)
print ('accuracy_train：', accuracy_score(ypca_train, randomforest.predict(xpca_train)))
print ('accuracy_test：', accuracy_score(ypca_test, randomforest.predict(xpca_test)))

print ('Kappa_train：', cohen_kappa_score(ypca_train, randomforest.predict(xpca_train)))
print ('Kappa_test：', cohen_kappa_score(ypca_test, randomforest.predict(xpca_test)))

print ('confusion_matrix_train：')
print ( confusion_matrix(ypca_train, randomforest.predict(xpca_train)))
print ('confusion_matrix_test：')
print ( confusion_matrix(ypca_test, randomforest.predict(xpca_test)))

accuracy_train： 0.9907235621521335
accuracy_test： 0.9523809523809523
Kappa_train： 0.9881071110208909
Kappa_test： 0.9373999162375897
confusion_matrix_train：
[[161   0   1   0   0   0   0]
 [  0 141   0   0   0   0   0]
 [  2   0  70   2   0   0   0]
 [  0   0   0 102   0   0   0]
 [  0   0   0   0  39   0   0]
 [  0   0   0   0   0  14   0]
 [  0   0   0   0   0   0   7]]
confusion_matrix_test：
[[74  0  3  1  0  0  0]
 [ 0 59  0  0  0  0  0]
 [ 2  0 22  2  0  0  0]
 [ 2  0  0 46  0  0  0]
 [ 0  0  0  1 10  0  0]
 [ 0  0  0  0  0  6  0]
 [ 0  0  0  0  0  0  3]]


In [53]:
randomforest.fit(xIca_train, yIca_train)
print ('accuracy_train：', accuracy_score(yIca_train, randomforest.predict(xIca_train)))
print ('accuracy_test：', accuracy_score(yIca_test, randomforest.predict(xIca_test)))

print ('Kappa_train：', cohen_kappa_score(yIca_train, randomforest.predict(xIca_train)))
print ('Kappa_test：', cohen_kappa_score(yIca_test, randomforest.predict(xIca_test)))

print ('confusion_matrix_train：')
print ( confusion_matrix(yIca_train, randomforest.predict(xIca_train)))
print ('confusion_matrix_test：')
print ( confusion_matrix(yIca_test, randomforest.predict(xIca_test)))

accuracy_train： 0.9851576994434137
accuracy_test： 0.961038961038961
Kappa_train： 0.980809883444074
Kappa_test： 0.9494836593366541
confusion_matrix_train：
[[175   0   0   0   0   0   0]
 [  0 135   0   0   0   0   0]
 [  1   0  72   1   0   0   0]
 [  3   0   3  93   0   0   0]
 [  0   0   0   0  34   0   0]
 [  0   0   0   0   0  14   0]
 [  0   0   0   0   0   0   8]]
confusion_matrix_test：
[[65  0  0  0  0  0  0]
 [ 0 65  0  0  0  0  0]
 [ 2  0 23  1  0  0  0]
 [ 4  0  1 46  0  0  0]
 [ 1  0  0  0 15  0  0]
 [ 0  0  0  0  0  6  0]
 [ 0  0  0  0  0  0  2]]


In [54]:
randomforest.fit(xlle_train, ylle_train)
print ('accuracy_train：', accuracy_score(ylle_train, randomforest.predict(xlle_train)))
print ('accuracy_test：', accuracy_score(ylle_test, randomforest.predict(xlle_test)))

print ('Kappa_train：', cohen_kappa_score(ylle_train, randomforest.predict(xlle_train)))
print ('Kappa_test：', cohen_kappa_score(ylle_test, randomforest.predict(xlle_test)))

print ('confusion_matrix_train：')
print ( confusion_matrix(ylle_train, randomforest.predict(xlle_train)))
print ('confusion_matrix_test：')
print ( confusion_matrix(ylle_test, randomforest.predict(xlle_test)))

accuracy_train： 0.987012987012987
accuracy_test： 0.9264069264069265
Kappa_train： 0.9832705925127809
Kappa_test： 0.9050095546793739
confusion_matrix_train：
[[158   0   2   3   0   0   0]
 [  0 144   0   0   0   0   0]
 [  1   0  66   0   0   0   0]
 [  0   0   0 108   0   0   0]
 [  0   0   0   0  38   0   0]
 [  0   0   0   0   0  12   0]
 [  1   0   0   0   0   0   6]]
confusion_matrix_test：
[[68  0  7  2  0  0  0]
 [ 0 56  0  0  0  0  0]
 [ 3  0 30  0  0  0  0]
 [ 4  0  1 37  0  0  0]
 [ 0  0  0  0 12  0  0]
 [ 0  0  0  0  0  8  0]
 [ 0  0  0  0  0  0  3]]


In [55]:
from sklearn.datasets import make_classification
from sklearn.ensemble import GradientBoostingClassifier
GradientBoosting1 = GradientBoostingClassifier(max_depth=2)
GradientBoosting2 = GradientBoostingClassifier(random_state=10,max_depth=3,min_samples_split=30,min_samples_leaf=10)

In [56]:
GradientBoosting1.fit(x_train, y_train)
print ('accuracy_train：', accuracy_score(y_train, GradientBoosting1.predict(x_train)))
print ('accuracy_test：', accuracy_score(y_test, GradientBoosting1.predict(x_test)))

print ('Kappa_train：', cohen_kappa_score(y_train, GradientBoosting1.predict(x_train)))
print ('Kappa_test：', cohen_kappa_score(y_test, GradientBoosting1.predict(x_test)))

print ('confusion_matrix_train：')
print ( confusion_matrix(y_train, GradientBoosting1.predict(x_train)))
print ('confusion_matrix_test：')
print ( confusion_matrix(y_test, GradientBoosting1.predict(x_test)))

accuracy_train： 1.0
accuracy_test： 0.9264069264069265
Kappa_train： 1.0
Kappa_test： 0.905048600029015
confusion_matrix_train：
[[175   0   0   0   0   0   0]
 [  0 136   0   0   0   0   0]
 [  0   0  67   0   0   0   0]
 [  0   0   0 105   0   0   0]
 [  0   0   0   0  32   0   0]
 [  0   0   0   0   0  16   0]
 [  0   0   0   0   0   0   8]]
confusion_matrix_test：
[[61  0  1  3  0  0  0]
 [ 0 64  0  0  0  0  0]
 [ 2  0 29  2  0  0  0]
 [ 4  0  2 39  0  0  0]
 [ 0  1  0  0 17  0  0]
 [ 0  0  0  0  0  4  0]
 [ 2  0  0  0  0  0  0]]


In [57]:
GradientBoosting1.fit(xpca_train, ypca_train)
print ('accuracy_train：', accuracy_score(ypca_train, GradientBoosting1.predict(xpca_train)))
print ('accuracy_test：', accuracy_score(ypca_test, GradientBoosting1.predict(xpca_test)))

print ('Kappa_train：', cohen_kappa_score(ypca_train, GradientBoosting1.predict(xpca_train)))
print ('Kappa_test：', cohen_kappa_score(ypca_test, GradientBoosting1.predict(xpca_test)))

print ('confusion_matrix_train：')
print ( confusion_matrix(ypca_train, GradientBoosting1.predict(xpca_train)))
print ('confusion_matrix_test：')
print ( confusion_matrix(ypca_test, GradientBoosting1.predict(xpca_test)))

accuracy_train： 1.0
accuracy_test： 0.961038961038961
Kappa_train： 1.0
Kappa_test： 0.9488573466827385
confusion_matrix_train：
[[162   0   0   0   0   0   0]
 [  0 141   0   0   0   0   0]
 [  0   0  74   0   0   0   0]
 [  0   0   0 102   0   0   0]
 [  0   0   0   0  39   0   0]
 [  0   0   0   0   0  14   0]
 [  0   0   0   0   0   0   7]]
confusion_matrix_test：
[[75  0  2  0  1  0  0]
 [ 0 59  0  0  0  0  0]
 [ 0  0 25  1  0  0  0]
 [ 1  0  0 47  0  0  0]
 [ 2  0  0  0  7  0  2]
 [ 0  0  0  0  0  6  0]
 [ 0  0  0  0  0  0  3]]


In [58]:
GradientBoosting1.fit(xIca_train, yIca_train)
print ('accuracy_train：', accuracy_score(yIca_train, GradientBoosting1.predict(xIca_train)))
print ('accuracy_test：', accuracy_score(yIca_test, GradientBoosting1.predict(xIca_test)))

print ('Kappa_train：', cohen_kappa_score(yIca_train, GradientBoosting1.predict(xIca_train)))
print ('Kappa_test：', cohen_kappa_score(yIca_test, GradientBoosting1.predict(xIca_test)))

print ('confusion_matrix_train：')
print ( confusion_matrix(yIca_train, GradientBoosting1.predict(xIca_train)))
print ('confusion_matrix_test：')
print ( confusion_matrix(yIca_test, GradientBoosting1.predict(xIca_test)))

accuracy_train： 1.0
accuracy_test： 0.987012987012987
Kappa_train： 1.0
Kappa_test： 0.9832044788056519
confusion_matrix_train：
[[175   0   0   0   0   0   0]
 [  0 135   0   0   0   0   0]
 [  0   0  74   0   0   0   0]
 [  0   0   0  99   0   0   0]
 [  0   0   0   0  34   0   0]
 [  0   0   0   0   0  14   0]
 [  0   0   0   0   0   0   8]]
confusion_matrix_test：
[[65  0  0  0  0  0  0]
 [ 0 65  0  0  0  0  0]
 [ 0  0 26  0  0  0  0]
 [ 2  0  0 49  0  0  0]
 [ 0  1  0  0 15  0  0]
 [ 0  0  0  0  0  6  0]
 [ 0  0  0  0  0  0  2]]


In [59]:
GradientBoosting1.fit(xlle_train, ylle_train)
print ('accuracy_train：', accuracy_score(ylle_train, GradientBoosting1.predict(xlle_train)))
print ('accuracy_test：', accuracy_score(ylle_test, GradientBoosting1.predict(xlle_test)))

print ('Kappa_train：', cohen_kappa_score(ylle_train, GradientBoosting1.predict(xlle_train)))
print ('Kappa_test：', cohen_kappa_score(ylle_test, GradientBoosting1.predict(xlle_test)))

print ('confusion_matrix_train：')
print ( confusion_matrix(ylle_train, GradientBoosting1.predict(xlle_train)))
print ('confusion_matrix_test：')
print ( confusion_matrix(ylle_test, GradientBoosting1.predict(xlle_test)))

accuracy_train： 1.0
accuracy_test： 0.9696969696969697
Kappa_train： 1.0
Kappa_test： 0.9606396962173215
confusion_matrix_train：
[[163   0   0   0   0   0   0]
 [  0 144   0   0   0   0   0]
 [  0   0  67   0   0   0   0]
 [  0   0   0 108   0   0   0]
 [  0   0   0   0  38   0   0]
 [  0   0   0   0   0  12   0]
 [  0   0   0   0   0   0   7]]
confusion_matrix_test：
[[75  0  2  0  0  0  0]
 [ 0 56  0  0  0  0  0]
 [ 2  0 31  0  0  0  0]
 [ 2  0  0 40  0  0  0]
 [ 0  0  0  0 12  0  0]
 [ 0  0  0  0  0  8  0]
 [ 1  0  0  0  0  0  2]]


In [60]:
from sklearn.neural_network import MLPClassifier

In [61]:
help(MLPClassifier)

Help on class MLPClassifier in module sklearn.neural_network.multilayer_perceptron:

class MLPClassifier(BaseMultilayerPerceptron, sklearn.base.ClassifierMixin)
 |  MLPClassifier(hidden_layer_sizes=(100,), activation='relu', solver='adam', alpha=0.0001, batch_size='auto', learning_rate='constant', learning_rate_init=0.001, power_t=0.5, max_iter=200, shuffle=True, random_state=None, tol=0.0001, verbose=False, warm_start=False, momentum=0.9, nesterovs_momentum=True, early_stopping=False, validation_fraction=0.1, beta_1=0.9, beta_2=0.999, epsilon=1e-08, n_iter_no_change=10)
 |  
 |  Multi-layer Perceptron classifier.
 |  
 |  This model optimizes the log-loss function using LBFGS or stochastic
 |  gradient descent.
 |  
 |  .. versionadded:: 0.18
 |  
 |  Parameters
 |  ----------
 |  hidden_layer_sizes : tuple, length = n_layers - 2, default (100,)
 |      The ith element represents the number of neurons in the ith
 |      hidden layer.
 |  
 |  activation : {'identity', 'logistic', 'tan

In [62]:
MLP=MLPClassifier(random_state=1,activation ="relu",solver="lbfgs",max_iter=500,beta_1=0.7,beta_2=0.7,hidden_layer_sizes=(70,))

In [63]:
MLP.fit(x_train, y_train)
print ('accuracy_train：', accuracy_score(y_train, MLP.predict(x_train)))
print ('accuracy_test：', accuracy_score(y_test, MLP.predict(x_test)))

print ('Kappa_train：', cohen_kappa_score(y_train, MLP.predict(x_train)))
print ('Kappa_test：', cohen_kappa_score(y_test, MLP.predict(x_test)))

print ('confusion_matrix_train：')
print ( confusion_matrix(y_train, MLP.predict(x_train)))
print ('confusion_matrix_test：')
print ( confusion_matrix(y_test, MLP.predict(x_test)))

accuracy_train： 0.9851576994434137
accuracy_test： 0.9826839826839827
Kappa_train： 0.9807877383710568
Kappa_test： 0.9777638735139818
confusion_matrix_train：
[[172   0   1   2   0   0   0]
 [  0 136   0   0   0   0   0]
 [  0   0  67   0   0   0   0]
 [  5   0   0 100   0   0   0]
 [  0   0   0   0  32   0   0]
 [  0   0   0   0   0  16   0]
 [  0   0   0   0   0   0   8]]
confusion_matrix_test：
[[64  0  1  0  0  0  0]
 [ 0 64  0  0  0  0  0]
 [ 0  0 33  0  0  0  0]
 [ 3  0  0 42  0  0  0]
 [ 0  0  0  0 18  0  0]
 [ 0  0  0  0  0  4  0]
 [ 0  0  0  0  0  0  2]]


In [64]:
print (MLP.score(x_test,y_test))
print (MLP.n_layers_)
print (MLP.loss_)

0.9826839826839827
3
0.06759671597337549
